### ISSUE TITLE
Suggestion: Order of sliders to better match workflow?

### ISSUE THREAD

**Issue by JonathanMaccollum** [mikec1485/GHS#1]
Absolutely love this script, and have recently become a fan. After having processed a number of data sets with this script, and attempted to help others get up to speed on it, and studying the documentation it seems that the order of operations a user follows first starts with the selection of the Symmetry Point, then the Local Stretch Intensity, then finally as a last step shift the Strength slider.  If this is indeed correct, consider reordering the sliders to fit the workflow.

Symmetry Point at the top (of the three main sliders)
Local Stretch Intensity second
Strength Factor Third

**Comment by mikec1485** [comment]
Thank you for your comments and helping others get up to speed. We will consider this suggestion.

**Comment by mikec1485** [comment]
I have just released version 2.  Having taken soundings from other GHS users I have kept the slider order unchanged.

**Comment by JonathanMaccollum** [comment]
Thanks for the consideration.
