### ISSUE TITLE
Enhancement Request: Further leveraging the histogram to adjust inputs

### ISSUE THREAD

**Issue by JonathanMaccollum** [mikec1485/GHS#17]
Since the 2.1 release added the ability to double-click on a portion of the histogram to adjust the "Pan" input field. It would be useful to have some similar enhancements for the following use cases: (In order of most frequently used for me personally, it would be interested to know others most histogram-influenced inputs.) 

* Adjust the Symmetry point (SP) input: The majority of the time when clicking on the histogram, the readout section is used to help select this input, and would be nice to not have to manually key that in. Perhaps a Ctrl+Click option for this when the Stretch Factor is GHS?
* Adjust the black point when in linear stretch
* Adjust the Highlight prot. point (HP): Perhaps an Alt+Click option for this?

**Comment by mikec1485** [comment]
This has been included in V2.1.  Once you have selected a point on the histogram you can click on the reset button to the right of the relevant parameter slider - this will transfer the histogram readout value to that parameter.  This will work for SP, HP, LP and in the linear stretch for BP and WP.

**Comment by JonathanMaccollum** [comment]
Gotcha! That works pretty well! It would be useful to not have to move the mouse between the area on the histogram and the reset button each time to make the fine adjustments. For example, you could just click on a point in the histogram, see it's effect on the preview, and make slight movements with the mouse to refine without move the cursor back and forth.

**Comment by mikec1485** [comment]
Interesting - I will have a think about that.

**Comment by JonathanMaccollum** [comment]
Sweet! Can't wait to check this out!

**Comment by JonathanMaccollum** [comment]
Hey Mike, took a little bit to figure out how to get that link to work, but once I did it's working great!
Thanks!
