### ISSUE TITLE
Preview Stretch in the main dialog box

### ISSUE THREAD

**Issue by JonathanMaccollum** [mikec1485/GHS#2]
Please consider allowing the preview functionality to exist on the same dialog box as the main inputs. The image icon that launches a second dialog box becomes blocking and makes it difficult to make fine tune adjustments and getting updated feedback.

Thanks!

**Comment by mikec1485** [comment]
Thanks. This one is already on my “to do” list!

**Comment by mikec1485** [comment]
I have just released version 2 which now includes real-time preview functionality on the main dialog box.

**Comment by JonathanMaccollum** [comment]
Oh fantastic! Looking forward to trying it out!
