### ISSUE TITLE
PixelMath History difference between v1 and v2

### ISSUE THREAD

**Issue by JonathanMaccollum** [mikec1485/GHS#5]
One of the excellent features in v1 of GHS was that one could replay the stretching operations from one image to another by re-applying the pixelmath processes stored in the history of an image (Dragging the icons from History Explorer in pixinsight).  The input parameters were persisted with the pixelmath tools that were used allowing it to be an easy operation to drag and drop.  In v2 it appears that this has gone away, and instead left with an unhelpful "_ghs_temp" expression that doesn't work once the script exits.

I assume this was done to help eliminate the unnecessary re-calculation when one was already applied for the new preview functionality, but this regression is one that is missed.

While one can of course save the values used, and re-launch the process to run them again on subsequent images this takes quite a bit more time to key in the exact same stretch from one image to another.

**Comment by mikec1485** [comment]
This change in behaviour reflects the more complex stretch types now available (eg luminance, saturation and colour) which involve extracting layers, operating on them, potentially applying masks etc.  It is possible simply to create an instance of any stretch by dragging the triangle at the bottom left of the dialog onto the workspace.  This would allow you to keep a record of stretches and these instances can be applied to a new image by dragging and dropping the instance you have created onto the new image without having to fire up the script at all.  Does this meet what you want?

**Comment by JonathanMaccollum** [comment]
Yes, I believe it does make for a usable workaround.  It would be a pretty good improvement if the history of the image were to reference this Script process with parameter information stored (instead of storing the unhelpful pixel math that's in place today, and it'd be even more friendly than the raw pixelmath stored in v1.)  I don't often know which stretches I want to "keep" until after I have finished (maybe still dependent on the undo/redo functionality at this point) so it'd be nice if the image history stored the parameters necessary to re-apply, or if the "Save your log" included a process container with those applied (excluding those that were undone).  I think there's a way to accomplish this in the PSJR to accomplish. If I can figure out the former at least, I'll submit a PR your way. Thanks!

**Comment by mikec1485** [comment]
Interesting thoughts.  I will have a think about what could be done.

**Comment by mikec1485** [comment]
View history is saved in the "processing" property of the "view" object.  This is a read only property and there are no methods of the view object that allow modification of it.  Basically, what gets written to the view history is outside any control from the program as far as I can see.  SoI think that approach is a non-starter.

The alternative of leveraging off the "stretch  log" is the way to go I think.  The logic of discarding undone stretches etc is all implemented already in that log.  I would like to add an option of saving to process icons - this would create a new process container for each image worked on in the current session.  Each process container would contain process icons for each stretch undertaken in the current session on that image.

That's the good news, the less good news is that the PJSR does not currently provide access to create new process icons, process containers etc.  Juan Conejero is, I understand, planning to include a new PJSR "Workspace" object in v1.8.9 which will give the programatic control to achieve what we want.  I know Juan has been working hard on v1.8.9 so hopefully the wait won't be too long!

So, I think the workaround of saving an instance manually will need to be the way to go for now. You can still undo/redo until you are happy with the stretch (although the preview, perhaps, makes this less necessary), when you are happy create the process instance by dragging the triangle o the workspace - they will be numerically ordered for easy identification of stretch order.  Then, when finished and exited the script, create a process container and drag the process icons into it in the right order.

**Comment by mikec1485** [comment]
Pixinsight version 1.8.9 was released yesterday.  Unfortunately this did not include the new Workspace object.  However, Juan Conejero has told me this is still intended to be released along with other updates to the PJSR in due course.

**Comment by mikec1485** [comment]
I have a solution - will include with next release.

**Comment by JonathanMaccollum** [comment]
Exciting! Thanks for looking into it!

**Comment by JonathanMaccollum** [comment]
Excellent work on the 2.1 release! The improvement here looks great, and resolves the issue.
